require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.2

Metrics/BlockLength:
  CountAsOne: ["heredoc"]
  AllowedMethods:
    - configure
    - context
    - describe
    - it
    - namespace
    - shared_examples
    - shared_examples_for

Metrics/ClassLength:
  CountAsOne: ["heredoc"]

Metrics/ModuleLength:
  CountAsOne: ["heredoc"]

Metrics/MethodLength:
  CountAsOne: ["heredoc"]

Metrics/ParameterLists:
  Max: 4

Style/Documentation:
  Exclude:
    - "app/**/application_*.rb"
    - "app/controllers/**/*"
    - "app/models/**/*"
    - "config/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
